spring.jpa.hibernate.ddl-auto=update
spring.application.name=apppaniol
server.port=8080
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=jdbc:postgresql://localhost:5432/tec1?options=-c%20TimeZone%3DUTC
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}